Fixes AttributeERROR .tostring() with .tobytes()
In python 3.9 / 3.10  tostring() is triggering ATTRIBUTE ERROR , which unhandled was causing the software to end.
This can be fixed easily by using tobytes() instead.

Original error :
```  
File "/usr/local/lib/python3.9/dist-packages/peframe-6.0.3-py3.9.egg/peframe/modules/features.py", line 21, in xor_delta
return delta.tostring()[:-key_len]
AttributeError: 'array.array' object has no attribute 'tostring'
```